### ISSUE TITLE
Error in h(simpleError(msg, call)) :    error in evaluating the argument 'data' in selecting a method for function 'bubbles': unable to find an inherited method for function ‘index.res’ for signature ‘"FLStock"’

### ISSUE THREAD

**Issue by marcfarre12** [flr/FLXSA#10]
Hi,

I tried to run a FLXSA but I had an error in the residuals function:

Model: xsa_control <- FLXSA.control(x=NULL, tol=1e-09, maxit=150, min.nse=0.3, fse=1.5,
                             rage=0, qage=2, shk.n=TRUE, shk.f=TRUE, shk.yrs=3, shk.ages=2,
                             window=100, tsrange=20, tspower=0, vpa=FALSE)

# Log Residuals
ttl <- list(label="Log residuals for surveys for Parapenaeus longirostris in GSA 5", cex=1)
yttl <- list(label="log residuals", cex=0.8)
xttl <- list(cex=0.8)
stripttl <- list(cex=0.8)
ax <- list(cex=0.7)
par(mfrow=c(1,3))
bubbles(age~year, data=index.res(stk.xsa)[1,], bub.scale=5,
        main=ttl, ylab=yttl, xlab=xttl, scales=ax, par.strip.text=stripttl)

And here it appears the error: 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'data' in selecting a method for function 'bubbles': unable to find an inherited method for function ‘index.res’ for signature ‘"FLStock"’

Besides, for the same model I had another error in the "diagnostics" function using the FLEDA package:

diagnostics(stk.xsa)

And it appear the error: "Error in (function (classes, fdef, mtable)  : unable to find an inherited method for function ‘diagnostics’ for signature ‘"FLStock"’

Does anybody knows what can be happeing?

Thanks

**Comment by iagomosqueira** [comment]
I assume `stk.xsa` in your code is an `FLStock` object, updated using the `+` operation on the input `FLStock` and the results of calling `FLXSA`. But `index.res` needs to be called on the `FLXSA` object. For example

```
library(FLXSA)
data(ple4)
data(ple4.index)

res <- FLXSA(ple4, ple4.index)

is(res)

index.res(res)
```
You can then use `ggplotFL` to create your own bubbleplot, for example

```
library(ggplotFL)

ggplot(index.res(res), aes(x=year, y=age, size=data, fill=data > 0)) +
  geom_point(shape=21) +
  scale_fill_manual(values = c("gray40", "white"))
```

Same applies to diagnostics, which is a method in `FLXSA`, and applies to the output object.

```
diagnostics(res)
```

**Comment by marcfarre12** [comment]
Thank you for answering and for the support.

Yes, finally it was a problem of the calling of the function. It finally worked!

Many thankd for the help!

**Comment by iagomosqueira** [comment]
Great!
