### ISSUE TITLE
Failed to install on Ubuntu

### ISSUE THREAD

**Issue by GeoTuxMan** [flr/FLXSA#2]
Hi,

I try to install FLXSA on Ubuntu:
/usr/lib/R/etc/Makeconf:168: recipe for target 'fl__vpa.o' failed
make: *** [fl__vpa.o] Error 1
ERROR: compilation failed for package ‘FLXSA’
* removing ‘/home/george/R/x86_64-pc-linux-gnu-library/3.4/FLXSA’
Warning in install.packages :
  installation of package ‘/home/george/Downloads/FLXSA_2.5.tar.gz’ had non-zero exit status

Maybe do you have any idea.

Cheers !
George

**Comment by iagomosqueira** [comment]
Is this from the repository or from github?

I have Ubuntu 16.04 and either option install fine, with just some warnings about char to const conversion.

Can you try

```
devtools::install_github('flr/FLXSA')
```

**Comment by GeoTuxMan** [comment]
> devtools::install_github('flr/FLXSA')
Downloading GitHub repo flr/FLXSA@master
from URL https://api.github.com/repos/flr/FLXSA/zipball/master
Installing FLXSA
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore
--quiet CMD INSTALL  \
  '/tmp/Rtmpx4Wjp8/devtools12892c48aa71/flr-FLXSA-e832f9a'  \
  --library='/home/george/R/x86_64-pc-linux-gnu-library/3.4'
--install-tests

* installing *source* package ‘FLXSA’ ...
** libs
g++  -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2
-fdebug-prefix-map=/build/r-base-1q72bO/r-base-3.4.2=.
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
-D_FORTIFY_SOURCE=2 -g  -c fl__ctc.cpp -o fl__ctc.o
g++  -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2
-fdebug-prefix-map=/build/r-base-1q72bO/r-base-3.4.2=.
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
-D_FORTIFY_SOURCE=2 -g  -c fl__r.cpp -o fl__r.o
g++  -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2
-fdebug-prefix-map=/build/r-base-1q72bO/r-base-3.4.2=.
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
-D_FORTIFY_SOURCE=2 -g  -c fl__tun.cpp -o fl__tun.o
g++  -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2
-fdebug-prefix-map=/build/r-base-1q72bO/r-base-3.4.2=.
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
-D_FORTIFY_SOURCE=2 -g  -c fl__vpa.cpp -o fl__vpa.o
fl__vpa.cpp: In member function ‘void VirtualPopAnalysis::SetRange(LPSHORT,
LPSHORT, short int)’:
fl__vpa.cpp:61:25: error: ‘min’ was not declared in this scope
       MinAge   = (short)min(MinAge,  Age[i]);
                         ^~~
fl__vpa.cpp:61:25: note: suggested alternative: ‘sin’
       MinAge   = (short)min(MinAge,  Age[i]);
                         ^~~
                         sin
fl__vpa.cpp:62:25: error: ‘max’ was not declared in this scope
       MaxAge   = (short)max(MaxAge,  Age[i]);
                         ^~~
fl__vpa.cpp:62:25: note: suggested alternative: ‘fmax’
       MaxAge   = (short)max(MaxAge,  Age[i]);
                         ^~~
                         fmax
fl__vpa.cpp: In member function ‘void
VirtualPopAnalysis::CheckRangeWithCatch(short int)’:
fl__vpa.cpp:78:14: error: ‘max’ was not declared in this scope
    MinAge  = max(MinAge, pCatch->GetMinAge());
              ^~~
fl__vpa.cpp:78:14: note: suggested alternative: ‘fmax’
    MinAge  = max(MinAge, pCatch->GetMinAge());
              ^~~
              fmax
fl__vpa.cpp:80:17: error: ‘min’ was not declared in this scope
       MaxAge  = min(pCatch->GetMaxAge(),PlusGroup-1);
                 ^~~
fl__vpa.cpp:80:17: note: suggested alternative: ‘sin’
       MaxAge  = min(pCatch->GetMaxAge(),PlusGroup-1);
                 ^~~
                 sin
fl__vpa.cpp:82:14: error: ‘min’ was not declared in this scope
    MaxYear = min(MaxYear, pCatch->GetMaxYear());
              ^~~
fl__vpa.cpp:82:14: note: suggested alternative: ‘sin’
    MaxYear = min(MaxYear, pCatch->GetMaxYear());
              ^~~
              sin
fl__vpa.cpp: In member function ‘void VirtualPopAnalysis::SetM(short int,
double)’:
fl__vpa.cpp:88:20: error: ‘max’ was not declared in this scope
       M[min(MaxAge,max(MinAge,iAge))][iYear] = Value;
                    ^~~
fl__vpa.cpp:88:20: note: suggested alternative: ‘fmax’
       M[min(MaxAge,max(MinAge,iAge))][iYear] = Value;
                    ^~~
                    fmax
fl__vpa.cpp:88:9: error: ‘min’ was not declared in this scope
       M[min(MaxAge,max(MinAge,iAge))][iYear] = Value;
         ^~~
fl__vpa.cpp:88:9: note: suggested alternative: ‘sin’
       M[min(MaxAge,max(MinAge,iAge))][iYear] = Value;
         ^~~
         sin
fl__vpa.cpp: In member function ‘void VirtualPopAnalysis::SetM(short int,
short int, double)’:
fl__vpa.cpp:93:17: error: ‘max’ was not declared in this scope
    M[min(MaxAge,max(MinAge,iAge))][min(MaxYear,max(MinYear,iYear))] =
Value;
                 ^~~
fl__vpa.cpp:93:17: note: suggested alternative: ‘fmax’
    M[min(MaxAge,max(MinAge,iAge))][min(MaxYear,max(MinYear,iYear))] =
Value;
                 ^~~
                 fmax
fl__vpa.cpp:93:6: error: ‘min’ was not declared in this scope
    M[min(MaxAge,max(MinAge,iAge))][min(MaxYear,max(MinYear,iYear))] =
Value;
      ^~~
fl__vpa.cpp:93:6: note: suggested alternative: ‘sin’
    M[min(MaxAge,max(MinAge,iAge))][min(MaxYear,max(MinYear,iYear))] =
Value;
      ^~~
      sin
fl__vpa.cpp: In member function ‘void VirtualPopAnalysis::SetF(short int,
short int, double)’:
fl__vpa.cpp:98:17: error: ‘max’ was not declared in this scope
    F[min(MaxAge,max(MinAge,iAge))][min(MaxYear,max(MinYear,iYear))] =
Value;
                 ^~~
fl__vpa.cpp:98:17: note: suggested alternative: ‘fmax’
    F[min(MaxAge,max(MinAge,iAge))][min(MaxYear,max(MinYear,iYear))] =
Value;
                 ^~~
                 fmax
fl__vpa.cpp:98:6: error: ‘min’ was not declared in this scope
    F[min(MaxAge,max(MinAge,iAge))][min(MaxYear,max(MinYear,iYear))] =
Value;
      ^~~
fl__vpa.cpp:98:6: note: suggested alternative: ‘sin’
    F[min(MaxAge,max(MinAge,iAge))][min(MaxYear,max(MinYear,iYear))] =
Value;
      ^~~
      sin
fl__vpa.cpp: In member function ‘double VirtualPopAnalysis::GetN(short int,
short int)’:
fl__vpa.cpp:148:11: error: ‘max’ was not declared in this scope
    return max(0.0,N[iAge][iYear]);
           ^~~
fl__vpa.cpp:148:11: note: suggested alternative: ‘fmax’
    return max(0.0,N[iAge][iYear]);
           ^~~
           fmax
fl__vpa.cpp: In member function ‘double VirtualPopAnalysis::GetF(short int,
short int)’:
fl__vpa.cpp:153:25: error: ‘max’ was not declared in this scope
    return
max(0.0,F[min(max(iAge,MinAge),MaxAge)][min(max(iYear,MinYear),MaxYear)]);
                         ^~~
fl__vpa.cpp:153:25: note: suggested alternative: ‘fmax’
    return
max(0.0,F[min(max(iAge,MinAge),MaxAge)][min(max(iYear,MinYear),MaxYear)]);
                         ^~~
                         fmax
fl__vpa.cpp:153:21: error: ‘min’ was not declared in this scope
    return
max(0.0,F[min(max(iAge,MinAge),MaxAge)][min(max(iYear,MinYear),MaxYear)]);
                     ^~~
fl__vpa.cpp:153:21: note: suggested alternative: ‘sin’
    return
max(0.0,F[min(max(iAge,MinAge),MaxAge)][min(max(iYear,MinYear),MaxYear)]);
                     ^~~
                     sin
fl__vpa.cpp:153:11: error: ‘max’ was not declared in this scope
    return
max(0.0,F[min(max(iAge,MinAge),MaxAge)][min(max(iYear,MinYear),MaxYear)]);
           ^~~
fl__vpa.cpp:153:11: note: suggested alternative: ‘fmax’
    return
max(0.0,F[min(max(iAge,MinAge),MaxAge)][min(max(iYear,MinYear),MaxYear)]);
           ^~~
           fmax
fl__vpa.cpp: In member function ‘double VirtualPopAnalysis::GetM(short
int)’:
fl__vpa.cpp:158:25: error: ‘max’ was not declared in this scope
    return max(0.0,M[min(max(iAge,MinAge),MaxAge)][MinYear]);
                         ^~~
fl__vpa.cpp:158:25: note: suggested alternative: ‘fmax’
    return max(0.0,M[min(max(iAge,MinAge),MaxAge)][MinYear]);
                         ^~~
                         fmax
fl__vpa.cpp:158:21: error: ‘min’ was not declared in this scope
    return max(0.0,M[min(max(iAge,MinAge),MaxAge)][MinYear]);
                     ^~~
fl__vpa.cpp:158:21: note: suggested alternative: ‘sin’
    return max(0.0,M[min(max(iAge,MinAge),MaxAge)][MinYear]);
                     ^~~
                     sin
fl__vpa.cpp:158:11: error: ‘max’ was not declared in this scope
    return max(0.0,M[min(max(iAge,MinAge),MaxAge)][MinYear]);
           ^~~
fl__vpa.cpp:158:11: note: suggested alternative: ‘fmax’
    return max(0.0,M[min(max(iAge,MinAge),MaxAge)][MinYear]);
           ^~~
           fmax
fl__vpa.cpp: In member function ‘double VirtualPopAnalysis::GetM(short int,
short int)’:
fl__vpa.cpp:163:25: error: ‘max’ was not declared in this scope
    return
max(0.0,M[min(max(iAge,MinAge),MaxAge)][min(max(iYear,MinYear),MaxYear)]);
                         ^~~
fl__vpa.cpp:163:25: note: suggested alternative: ‘fmax’
    return
max(0.0,M[min(max(iAge,MinAge),MaxAge)][min(max(iYear,MinYear),MaxYear)]);
                         ^~~
                         fmax
fl__vpa.cpp:163:21: error: ‘min’ was not declared in this scope
    return
max(0.0,M[min(max(iAge,MinAge),MaxAge)][min(max(iYear,MinYear),MaxYear)]);
                     ^~~
fl__vpa.cpp:163:21: note: suggested alternative: ‘sin’
    return
max(0.0,M[min(max(iAge,MinAge),MaxAge)][min(max(iYear,MinYear),MaxYear)]);
                     ^~~
                     sin
fl__vpa.cpp:163:11: error: ‘max’ was not declared in this scope
    return
max(0.0,M[min(max(iAge,MinAge),MaxAge)][min(max(iYear,MinYear),MaxYear)]);
           ^~~
fl__vpa.cpp:163:11: note: suggested alternative: ‘fmax’
    return
max(0.0,M[min(max(iAge,MinAge),MaxAge)][min(max(iYear,MinYear),MaxYear)]);
           ^~~
           fmax
fl__vpa.cpp: In member function ‘bool
VirtualPopAnalysis::RunCohortAnalysis()’:
fl__vpa.cpp:171:20: error: ‘min’ was not declared in this scope
       for (iAge  = min(MaxAge, MaxYear - iYearClass); iAge >= max(MinAge,
MinYear - iYearClass); iAge--)
                    ^~~
fl__vpa.cpp:171:20: note: suggested alternative: ‘sin’
       for (iAge  = min(MaxAge, MaxYear - iYearClass); iAge >= max(MinAge,
MinYear - iYearClass); iAge--)
                    ^~~
                    sin
fl__vpa.cpp:171:63: error: ‘max’ was not declared in this scope
       for (iAge  = min(MaxAge, MaxYear - iYearClass); iAge >= max(MinAge,
MinYear - iYearClass); iAge--)
                                                               ^~~
fl__vpa.cpp:171:63: note: suggested alternative: ‘fmax’
       for (iAge  = min(MaxAge, MaxYear - iYearClass); iAge >= max(MinAge,
MinYear - iYearClass); iAge--)
                                                               ^~~
                                                               fmax
fl__vpa.cpp: In member function ‘bool VirtualPopAnalysis::RunVPA()’:
fl__vpa.cpp:205:19: error: ‘min’ was not declared in this scope
       for (iAge = min(MaxAge, MaxYear - iYearClass); iAge >= max(MinAge,
MinYear - iYearClass); iAge--)
                   ^~~
fl__vpa.cpp:205:19: note: suggested alternative: ‘sin’
       for (iAge = min(MaxAge, MaxYear - iYearClass); iAge >= max(MinAge,
MinYear - iYearClass); iAge--)
                   ^~~
                   sin
fl__vpa.cpp:205:62: error: ‘max’ was not declared in this scope
       for (iAge = min(MaxAge, MaxYear - iYearClass); iAge >= max(MinAge,
MinYear - iYearClass); iAge--)
                                                              ^~~
fl__vpa.cpp:205:62: note: suggested alternative: ‘fmax’
       for (iAge = min(MaxAge, MaxYear - iYearClass); iAge >= max(MinAge,
MinYear - iYearClass); iAge--)
                                                              ^~~
                                                              fmax
/usr/lib/R/etc/Makeconf:168: recipe for target 'fl__vpa.o' failed
make: *** [fl__vpa.o] Error 1
ERROR: compilation failed for package ‘FLXSA’
* removing ‘/home/george/R/x86_64-pc-linux-gnu-library/3.4/FLXSA’
Installation failed: Command failed (1)

2017-12-08 4:59 GMT-05:00 Iago Mosqueira <notifications@github.com>:

**Comment by iagomosqueira** [comment]
Can you tell me what version of gcc are you using?

gcc -v gives me, at the end of the output

gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)

**Comment by GeoTuxMan** [comment]
Ubuntu 17.10

gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)

2017-12-08 5:59 GMT-05:00 Iago Mosqueira <notifications@github.com>:

**Comment by iagomosqueira** [comment]
OK, I will have to setup a virtual system to test this. I assume some new checks in newer ggc versions are failing on the old codebase of FLXSA. I will get back to you as soon as I am able to devote some time to this.

**Comment by GeoTuxMan** [comment]
OK, great...many thanks !
Looking forward to your reply.

2017-12-08 6:11 GMT-05:00 Iago Mosqueira <notifications@github.com>:

**Comment by iagomosqueira** [comment]
Some changes to the definition of min and max appear to solve the problem. These changes bring other problems in gvv 4.8.4, so I am committing these changes under the gcc720 branch, for the time being

https://github.com/flr/FLXSA/tree/gcc720

I have not tested the results too much yet, any feedback most that welcome.

You can install using

```
devtools::install_github('flr/FLXSA', ref='gcc720')
```

**Comment by iagomosqueira** [comment]
Found a better fix, changing min/max to use std::min/max and the newer malloc. Some type casting along the way, as short gets changed to int if 1 is substracted.

So master branch appears to work now on both versions of gcc. Try with

```
devtools::install_github('flr/FLXSA')
```
