### ISSUE TITLE
SE of q.hat reported incorrectly in diagnostics() function

### ISSUE THREAD

**Issue by hgerritsen** [flr/FLXSA#7]
the diagnostics function calculates the se of the log q as follows:
```{r}
 S.E_Logq = round(c(sd(matrix(object@index.res[[f]], 
                  dim(object@index.res[[f]])[2], dim(object@index.res[[f]])[1], 
                  byrow = T), na.rm = T)), 4)
```
It therefore assumes the se is the same for all ages, when you look at the old VPA95 output, you get different se estimates for each age. You can replicate this by simply doing this:
```{r}
apply(object@index.res[[f]],1,sd)
```
presumably this is a bug in the diagnostics function

**Comment by iagomosqueira** [comment]
Does the output of diagnostics look OK now?

**Comment by hgerritsen** [comment]
Yeee!
Thanks

**Comment by hgerritsen** [comment]
Perfect, thanks
